# Generated by Django 4.1.4 on 2022-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('estateAgency', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
