# Generated by Django 4.1.4 on 2022-12-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
