# Generated by Django 4.1.4 on 2022-12-22 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('orders', '0002_alter_ordermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='categories.categorymodel'),
        ),
    ]
