version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    links:
      - database

  database:
    container_name: database
    image: postgres:15-alpine
    env_file:
      - .env.database
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database: